apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: standard-cluster1
  policyController:
    enabled: true
  git:
    syncRepo: https://github.com/samos123/acm-demo.git
    syncBranch: master
    secretType: none
    policyDir: "foo-corp"
